# Generated by Django 5.1.7 on 2025-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
