# Generated by Django 5.1.7 on 2025-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0002_alter_booking_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
    ]
