# Generated by Django 5.1.7 on 2025-04-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0002_vehicle_num_ratings_vehicle_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('owner', 'Vehicle Owner')], default='farmer', max_length=10),
            preserve_default=False,
        ),
    ]
