# Generated by Django 5.1.7 on 2025-04-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0004_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visible_to_farmer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='visible_to_owner',
            field=models.BooleanField(default=True),
        ),
    ]
