# Generated by Django 5.1.7 on 2025-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0005_booking_visible_to_farmer_booking_visible_to_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Owner_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
