# Generated by Django 5.1.7 on 2025-04-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0006_vehicle_owner_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Owner_location',
            new_name='owner_location',
        ),
    ]
