# Generated by Django 5.1.7 on 2025-04-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0007_vehicle_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cars',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='loc_from',
            new_name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loc_to',
        ),
    ]
